project_id = "ihfxzbrnupbufapybjyt"

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.hook.custom_access_token]
enabled = false

[auth.hook.send_sms]
enabled = false

[auth.hook.send_email]
enabled = true
uri = "https://ihfxzbrnupbufapybjyt.supabase.co/functions/v1/send-auth-email"

[functions.send-auth-email]
verify_jwt = false

[functions.send-scorecard-email]
verify_jwt = true

[functions.send-questionnaire-email]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.resend-user-invite]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-dealer-comparison-email]
verify_jwt = true

[functions.send-gm-overview-email]
verify_jwt = true

[functions.questionnaire-submit]
verify_jwt = false

[functions.questionnaire-validate]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-trend-report-email]
verify_jwt = true

[functions.send-kpi-trend-email]
verify_jwt = true

[functions.send-forecast-email]
verify_jwt = true
